# Generated by Django 3.1.7 on 2021-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210311_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
